### ISSUE TITLE
연관관계?문제..

### ISSUE THREAD

**Issue by objet0128** [objet0128/CRUD#1]
### 코드
```python
class Article(Base, BaseMixin):

    title = Column(String)
    content = Column(String)
    owner_id = Column(Integer, ForeignKey("user.id"))
    article_id = Column(Integer, ForeignKey("article.id"))
    user = relationship("User", back_populates="article")

class User(Base, BaseMixin):

    email = Column(String, unique=True, index=True)
    password = Column(String)
    information = Column(String)
    articles = relationship("Article", back_populates="user")
```

### 에러
```
raceback (most recent call last):
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 393, in _resolve_name
    rval = d[token]
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 372, in _access_cls
    return self.fallback[key]
KeyError: 'Article'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/dev/CRUD/app/api/main.py", line 20, in create_user
    exist_user = users.get_user_by_email(db, email=user.email)
  File "/Users/dev/CRUD/app/crud/users.py", line 20, in get_user_by_email
    return db.query(User).filter(User.email == email).first()
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2161, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 181, in expect
    insp._post_inspect
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 3500, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 3539, in _do_configure_registries
    mapper._post_configure_properties()
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 1958, in _post_configure_properties
    prop.init()
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 2145, in do_init
    self._process_dependent_arguments()
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 2240, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 2107, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "/Users/dev/Library/Caches/pypoetry/virtualenvs/crud-MW-vHV-d-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Article' failed to locate a name ('Article'). If this is a class name, consider adding this relationship() to the <class 'app.models.users.User'> class after both dependent classes have been defined.

```

**Comment by objet0128** [comment]
https://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/database/sqlalchemy.html#importing-all-sqlalchemy-models - Importing all SQLAlchemy Models 참고
